# Generated by Django 2.1.15 on 2020-02-20 11:54

from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureId', models.AutoField(primary_key=True, serialize=False)),
                ('pictureData', models.TextField(default='https://static.wixstatic.com/media/b77fe464cfc445da9003a5383a3e1acf.jpg')),
                ('word', models.CharField(default='blank', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('avatarUrl', models.CharField(default='https://www.kindpng.com/picc/m/421-4212275_transparent-default-avatar-png-avatar-img-png-download.png', max_length=255)),
                ('language', models.CharField(default='english', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufbe.Pictures')),
            ],
        ),
        AddDefaultValue(
            model_name='pictures',
            name='pictureData', 
            value="https://static.wixstatic.com/media/b77fe464cfc445da9003a5383a3e1acf.jpg"
        ),
        AddDefaultValue(
            model_name='Users',
            name='score', value=0

        ),
        AddDefaultValue(
            model_name='Users',
            name='img_id', value=1
        ),
        AddDefaultValue(
            model_name='Users',
            name='avatarUrl', value='https://www.kindpng.com/picc/m/421-4212275_transparent-default-avatar-png-avatar-img-png-download.png'

        ),
        AddDefaultValue(
            model_name='Users',
            name='language', value='english'

        )
    ]
